/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.17.3
 * source: types/phonenumber.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace thebaasco.types {
    export class PhoneNumber extends pb_1.Message {
        constructor(data?: any[] | {
            sms_compatible?: boolean;
            number?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("sms_compatible" in data && data.sms_compatible != undefined) {
                    this.sms_compatible = data.sms_compatible;
                }
                if ("number" in data && data.number != undefined) {
                    this.number = data.number;
                }
            }
        }
        get sms_compatible() {
            return pb_1.Message.getField(this, 1) as boolean;
        }
        set sms_compatible(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get number() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set number(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            sms_compatible?: boolean;
            number?: string;
        }) {
            const message = new PhoneNumber({});
            if (data.sms_compatible != null) {
                message.sms_compatible = data.sms_compatible;
            }
            if (data.number != null) {
                message.number = data.number;
            }
            return message;
        }
        toObject() {
            const data: {
                sms_compatible?: boolean;
                number?: string;
            } = {};
            if (this.sms_compatible != null) {
                data.sms_compatible = this.sms_compatible;
            }
            if (this.number != null) {
                data.number = this.number;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.sms_compatible !== undefined)
                writer.writeBool(1, this.sms_compatible);
            if (typeof this.number === "string" && this.number.length)
                writer.writeString(2, this.number);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PhoneNumber {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PhoneNumber();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.sms_compatible = reader.readBool();
                        break;
                    case 2:
                        message.number = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PhoneNumber {
            return PhoneNumber.deserialize(bytes);
        }
    }
}
