/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.17.3
 * source: thebaasco/facade/onboarding/v1/facade_v1_onboarding.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../../google/protobuf/empty";
import * as dependency_2 from "./../../../tenant/onboarding/v1/onboarding_v1";
import * as grpc_1 from "@grpc/grpc-js";
export namespace thebaasco.facade.onboarding.v1 {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedOnboardingServiceService {
        static definition = {
            InitiateApplication: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/InitiateApplication",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.InitiateApplicationRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.InitiateApplicationRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdatePersonalDetails: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdatePersonalDetails",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdatePersonalDetailsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdatePersonalDetailsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateContactDetails: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateContactDetails",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateContactDetailsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateContactDetailsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateAccountDetails: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateAccountDetails",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateAccountDetailsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateAccountDetailsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateEmployment: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateEmployment",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateEmploymentRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateEmploymentRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateCustomerResidency: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateCustomerResidency",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateCustomerResidencyRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateCustomerResidencyRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateConsents: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateConsents",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateConsentsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateConsentsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateDisclosures: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateDisclosures",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateDisclosuresRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateDisclosuresRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateAddresses: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateAddresses",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateAddressesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateAddressesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateCommunicationPreferences: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/UpdateCommunicationPreferences",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateCommunicationPreferencesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.UpdateCommunicationPreferencesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            ValidateDocuments: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/ValidateDocuments",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.ValidateDocumentsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.ValidateDocumentsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            ValidateSelfie: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/ValidateSelfie",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.ValidateSelfieRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.ValidateSelfieRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            ValidateApplication: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/ValidateApplication",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.ValidateApplicationRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.ValidateApplicationRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            AcceptApplication: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/AcceptApplication",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.AcceptApplicationRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.AcceptApplicationRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            FinalizeApplicationCreateCustomer: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/FinalizeApplicationCreateCustomer",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateCustomerRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateCustomerRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            FinalizeApplicationCreateProduct: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/FinalizeApplicationCreateProduct",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateProductRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateProductRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            CancelApplication: {
                path: "/thebaasco.facade.onboarding.v1.OnboardingService/CancelApplication",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.thebaasco.tenant.onboarding.v1.CancelApplicationRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.thebaasco.tenant.onboarding.v1.CancelApplicationRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract InitiateApplication(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.InitiateApplicationRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdatePersonalDetails(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdatePersonalDetailsRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateContactDetails(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateContactDetailsRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateAccountDetails(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateAccountDetailsRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateEmployment(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateEmploymentRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateCustomerResidency(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateCustomerResidencyRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateConsents(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateConsentsRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateDisclosures(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateDisclosuresRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateAddresses(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateAddressesRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract UpdateCommunicationPreferences(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.UpdateCommunicationPreferencesRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract ValidateDocuments(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.ValidateDocumentsRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract ValidateSelfie(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.ValidateSelfieRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract ValidateApplication(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.ValidateApplicationRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract AcceptApplication(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.AcceptApplicationRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract FinalizeApplicationCreateCustomer(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateCustomerRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract FinalizeApplicationCreateProduct(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateProductRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract CancelApplication(call: grpc_1.ServerUnaryCall<dependency_2.thebaasco.tenant.onboarding.v1.CancelApplicationRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
    }
    export class OnboardingServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedOnboardingServiceService.definition, "OnboardingService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        InitiateApplication: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.InitiateApplicationRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.InitiateApplicationRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.InitiateApplication(message, metadata, options, callback);
        };
        UpdatePersonalDetails: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdatePersonalDetailsRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdatePersonalDetailsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdatePersonalDetails(message, metadata, options, callback);
        };
        UpdateContactDetails: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateContactDetailsRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateContactDetailsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateContactDetails(message, metadata, options, callback);
        };
        UpdateAccountDetails: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateAccountDetailsRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateAccountDetailsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateAccountDetails(message, metadata, options, callback);
        };
        UpdateEmployment: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateEmploymentRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateEmploymentRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateEmployment(message, metadata, options, callback);
        };
        UpdateCustomerResidency: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateCustomerResidencyRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateCustomerResidencyRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateCustomerResidency(message, metadata, options, callback);
        };
        UpdateConsents: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateConsentsRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateConsentsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateConsents(message, metadata, options, callback);
        };
        UpdateDisclosures: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateDisclosuresRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateDisclosuresRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateDisclosures(message, metadata, options, callback);
        };
        UpdateAddresses: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateAddressesRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateAddressesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateAddresses(message, metadata, options, callback);
        };
        UpdateCommunicationPreferences: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.UpdateCommunicationPreferencesRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.UpdateCommunicationPreferencesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateCommunicationPreferences(message, metadata, options, callback);
        };
        ValidateDocuments: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.ValidateDocumentsRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.ValidateDocumentsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.ValidateDocuments(message, metadata, options, callback);
        };
        ValidateSelfie: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.ValidateSelfieRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.ValidateSelfieRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.ValidateSelfie(message, metadata, options, callback);
        };
        ValidateApplication: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.ValidateApplicationRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.ValidateApplicationRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.ValidateApplication(message, metadata, options, callback);
        };
        AcceptApplication: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.AcceptApplicationRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.AcceptApplicationRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.AcceptApplication(message, metadata, options, callback);
        };
        FinalizeApplicationCreateCustomer: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateCustomerRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateCustomerRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.FinalizeApplicationCreateCustomer(message, metadata, options, callback);
        };
        FinalizeApplicationCreateProduct: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateProductRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.FinalizeApplicationCreateProductRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.FinalizeApplicationCreateProduct(message, metadata, options, callback);
        };
        CancelApplication: GrpcUnaryServiceInterface<dependency_2.thebaasco.tenant.onboarding.v1.CancelApplicationRequest, dependency_1.google.protobuf.Empty> = (message: dependency_2.thebaasco.tenant.onboarding.v1.CancelApplicationRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.CancelApplication(message, metadata, options, callback);
        };
    }
}
